### ISSUE TITLE
Create a sample applications

### ISSUE THREAD

**Issue by llacroix** [servo/rust-mozjs#134]
As there is not yet any kind of documentation on how to use the rust-mozjs binding of the jsapi. It would be cool to have something that mimmick the sample jsapi helloworld app from mozilla. (By documentation I mean user guide and not just reference documentation).

As some things are a bit different, I wasn't able to build an application that works like the minimal application here:

https://developer.mozilla.org/en-US/docs/Mozilla/Projects/SpiderMonkey/JSAPI_User_Guide

**Comment by jdm** [comment]
I agree that an example app would be nice to have, but I have no time to create it myself. I'm willing to help someone else set it up, however!

**Comment by jdm** [comment]
And yes, if that wiki page is up to date, it probably uses APIs that are 2.5 years newer than the ones available in this repository.

**Comment by llacroix** [comment]
I believe the helloworld program there has been the same for at least 2 years.

**Comment by zofrex** [comment]
Proposing closing this now that #165 has landed

**Comment by llacroix** [comment]
Cool thanks
