### ISSUE TITLE
Make Handle objects take lifetimes

### ISSUE THREAD

**Issue by michaelwu** [servo/rust-mozjs#153]
Handles are currently dangerous right now since they can outlive the Roots that they're taken from. We should make them take lifetimes to avoid that issue. This api is introduced in https://github.com/servo/rust-mozjs/pull/150

**Comment by nox** [comment]
Tried doing this, encountered https://github.com/rust-lang/rust/issues/10501 on the *Op function types.

**Comment by jdm** [comment]
My attempt lives at https://github.com/jdm/rust-mozjs/tree/handle and https://github.com/jdm/servo/tree/handles .

**Comment by marmistrz** [comment]
I'll work on this as a part of my Bachelor's thesis.

**Comment by marmistrz** [comment]
@jdm leaving a comment here since crowbot seems to be absent.
```
<marmistrz> Hi! I took a look at the following, unmerged try for lifetimed-Handle objects: https://github.com/servo/rust-mozjs/issues/153#issuecomment-136517685 
<marmistrz> What was the reason it was not merged straightaway?
<marmistrz> At first glance it looks just fine. (without deep digging through the code) Was it simply not tested enough?
<emilio> marmistrz: I bet it's because jdm didn't end up finding the time to fix all the usages in Servo... but you can ask him directly when he's back
```

**Comment by jdm** [comment]
There were build errors that I encountered that I was not sure how to solve. It would have been smart if I had left a record of them anywhere, but I am not smart unfortunately.

**Comment by jdm** [comment]
Rather, the rust-mozjs PR seemed fine. It was the Servo one that ran into difficulties.
