### ISSUE TITLE
Crashes on Runtime::new()

### ISSUE THREAD

**Issue by zofrex** [servo/rust-mozjs#163]
Test case:

```rust
extern crate js;

use js::rust::Runtime;

fn main() {
    let _r = Runtime::new();
}
```

Result: Crashes

[This is where it crashes on my machine](https://gist.github.com/zofrex/5827f4f22340c8a272a9) (OS X)

vers on IRC volunteered to try it too and got [this slightly different crash](http://pastebin.com/AnDPfQtf) on Fedora 22 ([valgrind output](http://pastebin.com/Exe7gEKd))

**Comment by michaelwu** [comment]
A `JS_Init` call is necessary first.

**Comment by zofrex** [comment]
I'm annoyed at myself for wasting my time, and your time... I'm not sure at what point the JS_Init got lost out of my code (from which I prepared this sample) but _of course_ it's necessary first.

Sorry!

**Comment by zofrex** [comment]
Note to anyone else passing: Runtime::new() used to include a JS_Init call, now it no longer does. This works:

```rust
    unsafe {
        JS_Init();
    }
    let r = Runtime::new();
```

**Comment by michaelwu** [comment]
JS_Init is new with the SM upgrade we had recently - the tests in this code don't use them either.

I recommend building with `--features js/debugmozjs` while developing which will enable assertions in SM. Many jsapi issues can be caught with that. The rest are usually caught by running with `JS_GC_ZEAL=4,1`.

**Comment by zofrex** [comment]
Thanks Michael, that's very helpful to know!
