### ISSUE TITLE
Errors are not being reported

### ISSUE THREAD

**Issue by zofrex** [servo/rust-mozjs#164]
Out of the box, the registered error reporting function is not being called for me. I've narrowed it down to these two lines in Runtime::new():

``` rust
            (*contextopts).set_dontReportUncaught_(true);
            (*contextopts).set_autoJSAPIOwnsErrorReporting_(true);
```

Unless both of these options are set to false, the error reporting function doesn't get called on error.

**Comment by Ms2ger** [comment]
`autoJSAPIOwnsErrorReporting` should definitely be true for Servo. Paging @bholley.

**Comment by bholley** [comment]
Yes. If you want to avoid an error reporting nightmare, Servo should do the following:
1: Set autoJSAPIOwnsErrorReporting and dontReportUncaught everywhere (hopefully on the single JSContext that Servo presumably has).
2: Register a "WarningOnlyErrorReporter", that behaves similarly to the one set by AutoJSAPI::TakeOwnershipOfErrorReporting.
3: Implementing an RAII class like AutoJSAPI, which handles errors when it gets popped off the stack.

**Comment by KishanV** [comment]
How can I enable error reporting on current rust-mozjs version....

**Comment by Ms2ger** [comment]
SpiderMonkey no longer calls a callback to report errors, just warnings (`SetWarningReporter`). You'll need to handle errors yourself when appropriate; there's [some code in Servo](https://github.com/servo/servo/blob/6c3e94805f74e78b091b37fe374af12ad2249528/components/script/dom/bindings/error.rs#L200) you might be able to reuse.
