### ISSUE TITLE
Builds fail on Win64 MSVC ABI

### ISSUE THREAD

**Issue by ghost** [servo/rust-mozjs#228]
I've tried twice on 2 different computers but it seems rust-mozjs fails when building on with the MSVC rust compiler. (I've built it with Debian x64 w/ Stable)

**Comment by jdm** [comment]
Since Servo doesn't support Windows yet, nobody has tried this, unfortunately.

**Comment by jdm** [comment]
That being said, if you paste the errors here we can try to help.

**Comment by valarauca** [comment]
I have no issue working in Linux. It was just a slow day at work so I pulled my profile and tried to run a cargo test just to see if it would compile. If its not a supported platform I understand.

**Comment by michaelwu** [comment]
The bindings are generated for itanium c++ mangling so msvc wouldn't work.

**Comment by jdm** [comment]
This works now.
