### ISSUE TITLE
Conversion to vector should throw a TypeError 

### ISSUE THREAD

**Issue by Ms2ger** [servo/rust-mozjs#237]
Code is in `src/conversions.rs`, in `impl<C: Clone, T: FromJSValConvertible<Config=C>> FromJSValConvertible for Vec<T> {`.

Use `throw_type_error()` for the case where `is_object()` is false. The error should be something along the lines of "value is not an object".

**Comment by stspyder** [comment]
@Ms2ger shouldn't we also throw a type error at https://github.com/servo/rust-mozjs/blob/master/src/conversions.rs#L517 for when a object without length property is passed on?

**Comment by Ms2ger** [comment]
I don't remember when that case can be hit. We probably should for now.

**Comment by jdm** [comment]
`new Blob({0: "foo"})`, I'm pretty sure.

**Comment by ecoal95** [comment]
Don't we already throw from the generated code if all the possible conversions fail?

**Comment by Ms2ger** [comment]
The contract for `from_jsval` says "If it returns `Err(())`, a JSAPI exception is pending." The handling in unions/overloads is broken, because we don't use for-of iteration, as we should. We'll have to figure out a way to do that correctly once the implementation here has been fixed.

**Comment by KiChjang** [comment]
Fixed by #238.
