### ISSUE TITLE
Consider having Runtime::new enter a request

### ISSUE THREAD

**Issue by Ms2ger** [servo/rust-mozjs#259]
https://github.com/servo/rust-mozjs/pull/258#issuecomment-213615809

> AFAICT, there's no need to ever enter more than one request - or leave that request. We don't call `js::SetActivityCallback`, and I'm pretty sure that's the only thing triggered by `rt->requestDepth` being set to or changed from `0`.

If that's true, we wouldn't have to deal with requests in any code downstream of this crate (which would make me very happy!).

**Comment by tschneidereit** [comment]
> 07:43 <till> jorendorff: what are requests for nowadays?
> 07:44 <jorendorff> yeah, not much - it's vestigial
> 07:44 <jorendorff> we should rip it out
> 07:50 <jonco> till: I don't think there's any interaction with requests in the rooting api

**Comment by Ms2ger** [comment]
See also discussion in https://bugzilla.mozilla.org/show_bug.cgi?id=1267297
