### ISSUE TITLE
Introduce something like CallArgs

### ISSUE THREAD

**Issue by evilpie** [servo/rust-mozjs#29]
Using barebones argv and argc is dangerous and annoying. We should add something like get CallArgsFromVp and have the CallArgs class be typesafe and fail on out of bounds access etc.

**Comment by zofrex** [comment]
This has mostly been done now:

```rust
unsafe extern "C" fn callback(context: *mut JSContext, argc: u32, vp: *mut Value) -> u8 {
    let args = CallArgs::from_vp(vp, argc);
    let arg = args.get(0);
    args.rval().set(UndefinedValue());
    return 1;
}
```

.length() would be a nice addition though, .requireAtLeast() would be even nicer.

**Comment by Ms2ger** [comment]
If you want to add those, I'd be happy to review
