### ISSUE TITLE
Review soundness of ObjectValue and friends.

### ISSUE THREAD

**Issue by nox** [servo/rust-mozjs#292]
These functions take a `&JSObject`, but `JSObject` is an empty type. This is worrying because doing just `*obj` on it is UB.

**Comment by Ms2ger** [comment]
Yeah, that was a stupid idea on my part. It should just take `*mut JSObject`.

**Comment by DemiMarie** [comment]
I have a PR coming – just doing a local build.

**Comment by emilio** [comment]
This is fixed now.
