### ISSUE TITLE
TypedArray::from method should protect against null pointers 

### ISSUE THREAD

**Issue by jdm** [servo/rust-mozjs#332]
We should add a testcase to `tests/typedarray.rs` that uses the `typedarray!` macro on `ptr::null_mut()`, and write code that correctly returns an Err value if that's encountered.

Code: `src/typedarray.rs`

**Comment by zakorgy** [comment]
@jdm I would like to try this.

**Comment by emilio** [comment]
Nice! Let us know if you need any help :)

**Comment by zakorgy** [comment]
Thanks @emilio. If I'm correct, the test case should be look like this:
``` rust
        rooted!(in(cx) let rval = ptr::null_mut());
        typedarray!(in(cx) let array: Uint8Array = rval.get());
        assert!(array.is_err());
```

**Comment by jdm** [comment]
That looks right!
