### ISSUE TITLE
Modify TypedArray::create API to accept either a length or an initial slice

### ISSUE THREAD

**Issue by jdm** [servo/rust-mozjs#336]
For cases when we create a new typed array with an initial slice, we always want to use the length of the provided slice. Passing the same length as another argument is redundant; we should use a custom enum argument instead (eg. `CreateWith::Length(5)` and `CreateWith::Slice(foo)`).

Code: `src/typedarray.rs`
Tests: `cargo test --name typedarray` (`tests/typedarray.rs`)

**Comment by simon-whitehead** [comment]
This looks like a great first PR. Mind if I give it a shot? I may need some guidance around code/test style but hopefully I won't need too much hand-holding.

**Comment by jdm** [comment]
Please do!

**Comment by simon-whitehead** [comment]
@jdm Are you able to give me some guidance/documentation around versioning? I imagine I'll be required to bump the crate version?

**Comment by jdm** [comment]
We use a git dependency for rust-mozjs the crate version doesn't actually matter for that case. This crate is also not published to crates.io, so we generally have not been updating the version.

**Comment by KiChjang** [comment]
Fixed by #337.
