### ISSUE TITLE
CompileOptionsWrapper::new should accept a &str instead of a C string pointer

### ISSUE THREAD

**Issue by jdm** [servo/rust-mozjs#518]
It's too easy to misuse, otherwise. We can do the rust->c string conversion inside the constructor.

**Comment by jdm** [comment]
https://github.com/servo/rust-mozjs/blob/5a50c377a4e1f55abc1286b74100a4cc35adc789/src/rust.rs#L928

**Comment by nicoabie** [comment]
@highfive: assign me

**Comment by nicoabie** [comment]
PR https://github.com/servo/rust-mozjs/pull/520 addresses this issue.
