### ISSUE TITLE
Issue with Building in GitHub Actions CI

### ISSUE THREAD

**Issue by Redfire75369** [servo/rust-mozjs#538]
I have started a new project embedding spidermonkey. Using the [workflow](https://github.com/servo/rust-mozjs/blob/maste/.github/workflows/rust.yml) in this project as a base, I created a GitHub workflow to test builds on 3 platforms.

However, of these three test builds, only the [MacOS](https://github.com/Redfire75369/spiderfire/runs/2112987217?check_suite_focus=true) build completed successfully. The other two, [Ubuntu](https://github.com/Redfire75369/spiderfire/runs/2112987200?check_suite_focus=true) and [Windows](https://github.com/Redfire75369/spiderfire/runs/2112987129?check_suite_focus=true) builds failed.

According to the SpiderMonkey developers in the #spidermonkey:mozilla.org Matrix Channel, the issue with the Linux build should have been fixed in SpiderMonkey 74. As for the issue with the Windows build, I have no leads yet.

These issues with building are all the more perplexing as I have successfully compiled this project both on Windows, and WSL Debian. Some others, who have tried to clone my [repository](https://github.com/Redfire75369/spiderfire) and compile it from source have also encountered similar issues to the GitHub Actions Linux build.

**Comment by sagudev** [comment]
Hm, your cargo.lock file says you are using old version of this repo. Try cargo update, and make sure workflow files are identical.

**Comment by Redfire75369** [comment]
I am aware that the version in `Cargo.lock` is outdated. Those who have cloned my repository have experienced improved results with `cargo update`. However, I do not see any reason that using the same version of `rust-mozjs` could result in different build results.

**Comment by sagudev** [comment]
I did quick check and your rust-mozjs commit was from the time there was no workflow in this repo. Current workflows are meant to be for newer versions because of PYTHON2 and other deps. So use exact workflow and latest revision and it would work. You can check this repos actions for proof.

**Comment by Redfire75369** [comment]
Ran `cargo update` and Windows build is failing locally now: https://paste.mozilla.org/nYmPUMBq

**Comment by sagudev** [comment]
I update in my fork: https://github.com/sagudev/spiderfire/runs/2121356009?check_suite_focus=true
the only problem is different ModuleEvaluate function. Will send you PR.

**Comment by jdm** [comment]
Sounds like this is solved.

**Comment by Redfire75369** [comment]
The issue with the workflows has been fixed, but the issue with a local windows build is still occuring.
See: https://gist.githubusercontent.com/Redfire75369/0c0573d3aeb6d66afcd709b5d0d07f3d/raw/dd11757a5809e2856c7eb15a9bd7c3402e1f8c0b/output.log

**Comment by sagudev** [comment]
Something is wrong with clang or vsbuild. Do you have both installed? Try to replicate workflow for windows on your pc.

**Comment by Redfire75369** [comment]
I just updated VSBuild so i don't think it's that, i'll try reinstalling/updating Clang

**Comment by sagudev** [comment]
Do not forget MozillaBuild.

**Comment by jdm** [comment]
Set CXX and CC to clang-cl; building with cl directly is unsupported.

**Comment by Redfire75369** [comment]
Might have to update this then? https://github.com/servo/mozjs/blob/master/README.md

**Comment by Redfire75369** [comment]
Good News: Build works properly now
