### ISSUE TITLE
Docs on doc.servo.org are outdated

### ISSUE THREAD

**Issue by Redfire75369** [servo/rust-mozjs#539]
https://doc.servo.org/mozjs/jsapi/fn.ModuleEvaluate.html shows only 2 parameters. 
However, according to `cargo doc` and the rust compiler, it has 3 parameters.

New Method Signature:
```rs
pub unsafe extern "C" fn ModuleEvaluate(cx: *mut JSContext, moduleRecord: Handle<*mut JSObject>, rval: MutableHandle<Value>) -> bool
```

**Comment by sagudev** [comment]
This is due to https://github.com/servo/rust-mozjs/pull/535 which was merged today, but I do not know how docs are updated on site.

**Comment by jdm** [comment]
The docs are updated every time a PR is merged to servo/servo. No way to avoid this, unfortunately.
